### ISSUE TITLE
Importing sergio in demo

### ISSUE THREAD

**Issue by agitter** [PayamDiba/SERGIO#2]
I had difficulties running the demo notebook `Demo/demo_run.ipynb` from the `Demo` directory because the `sergio` module wasn't found.  It could help new users to either provide instructions ([like this runpy tip](https://twitter.com/GaelVaroquaux/status/1194336723469316096)) for importing the module or put the demo code in the same directory as `sergio.py`.

I realize you plan to release an official package soon, which will solve this problem in the longer term.

There's also a typo in the notebook: `steady-state_input_GRN.txtt`

**Comment by PayamDiba** [comment]
The issue was resolved, thank you for mentioning it.

**Comment by PayamDiba** [comment]
> I had difficulties running the demo notebook `Demo/demo_run.ipynb` from the `Demo` directory because the `sergio` module wasn't found. It could help new users to either provide instructions ([like this runpy tip](https://twitter.com/GaelVaroquaux/status/1194336723469316096)) for importing the module or put the demo code in the same directory as `sergio.py`.
> 
> I realize you plan to release an official package soon, which will solve this problem in the longer term.
> 
> There's also a typo in the notebook: `steady-state_input_GRN.txtt`

**Comment by PayamDiba** [comment]
The issue was resolved, thank you for mentioning it.
