### ISSUE TITLE
error when running run_sergio.ipynb

### ISSUE THREAD

**Issue by PeterZZQ** [PayamDiba/SERGIO#4]
Hi,

I'm trying to use the differentiation simulation in `run_sergio.ipynb`, and I got an error which is like below. I use `python3.7.4`.

```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-9ff58ee8e660> in <module>
      4 sim = sergio(number_genes=100, number_bins = 6, number_sc = 300, noise_params = 0.2, decays=0.8, sampling_state = 1, noise_params_splice = 0.07, noise_type='dpd', dynamics=True, bifurcation_matrix= bMat)
      5 sim.build_graph(input_file_taregts ='data_sets/De-noised_100G_6T_300cPerT_dynamics_7_DS6/Interaction_cID_7.txt', input_file_regs='data_sets/De-noised_100G_6T_300cPerT_dynamics_7_DS6/Regs_cID_7.txt', shared_coop_state=2)
----> 6 sim.simulate_dynamics()
      7 exprU, exprS = sim.getExpressions_dynamics()
      8 exprU_clean = np.concatenate(exprU, axis = 1)

~/Documents/research/Simulators/code/SERGIO_simu/SERGIO/sergio.py in simulate_dynamics(self)
    837         for bi in self.binOrders_:
    838             print ("Start simulating new cell type")
--> 839             self.populate_with_parentCells_(bi)
    840             self.dynamics_CLE_simulator_(bi)
    841             print ("Done with current cell type")

~/Documents/research/Simulators/code/SERGIO_simu/SERGIO/sergio.py in populate_with_parentCells_(self, binID)
    634 
    635             for i in range(len(deltaU)):
--> 636                 g.append_Conc([self.binDict[parentBinID][g.ID].ss_U_ + deltaU[i]])
    637                 g.append_Conc_S([self.binDict[parentBinID][g.ID].ss_S_ + deltaS[i]])
    638 

~/Documents/research/Simulators/code/SERGIO_simu/SERGIO/gene.py in append_Conc(self, currConc)
     26 
     27     def append_Conc (self, currConc):
---> 28         if currConc < 0:
     29             currConc = 0
     30         self.Conc.append(currConc)

TypeError: '<' not supported between instances of 'list' and 'int'

```

**Comment by PayamDiba** [comment]
Did you get this error when running the dynamics simulation with the same input arguments as provided in run_sergio.ipynb? Also, what have you used for "bifurcation_matrix" argument? Please make sure that it's a numpy array of size #cell_types * #cell_types.

**Comment by PeterZZQ** [comment]
Hi, thanks for responding, I didn't change anything, I just run the notebook in the root directory, and the error came out. The steady-state works fine, but I truly need to run the dynamics feature as I need the velocity. 
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/37580703/85248024-ae53cc00-b41d-11ea-8cb8-6b1ed130c170.png">

**Comment by PeterZZQ** [comment]
And the error
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/37580703/85248103-e1965b00-b41d-11ea-98a7-df8b8b0c4f3a.png">

**Comment by PeterZZQ** [comment]
Oh, I get it, I think it's a small bug here, when I output the currConc, it gives [3.919013583331346], which is a list, and I think we should replace currConc with currConc with currConc[0] here.

**Comment by PeterZZQ** [comment]
I basically change two functions here 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/37580703/85249796-b6fad100-b422-11ea-9941-15e744fe281f.png">

**Comment by PeterZZQ** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/37580703/85250164-ce868980-b423-11ea-8ab9-6b9ea620de7e.png">
This seems to work fine.

**Comment by PeterZZQ** [comment]
By the way, I was wondering if the true simulation time can be obtained? With cell differentiation pattern benchmarking algorithms still requires true simulation time. I didn't find it in the readme.md

**Comment by PayamDiba** [comment]
> Oh, I get it, I think it's a small bug here, when I output the currConc, it gives [3.919013583331346], which is a list, and I think we should replace currConc with currConc[0] here.

Thanks for reporting this. But the modification you suggested might change the functionality of the tool in differentiation simulations. In fact, currConc needs to be a list as each list corresponds to a separate cell which is differentiating from its parent established type to another cell type. So please do not convert currConc from a list to a scalar. The issue is now resolved and you should be able to run it with no error. Please clone the new version and let me know if you still get an error.

**Comment by PayamDiba** [comment]
> By the way, I was wondering if the true simulation time can be obtained? Cell differentiation pattern benchmarking algorithms (like trajectory inference) still requires true simulation time. I didn't find it in the readme.md

Unfortunately, this is not currently available in SERGIO. We will work on this for future releases. What is often referred to as "pseudo-time" is the ordering of cells on a lineage evident in a reduced dimension representation (e.g. PCA) of cells. While this a coarse-grained (smoothed) representation of "cell times", SERGIO's time is more fine-grained to allow the capture of stochastic noise and it might cast the signal you need for benchmarking trajectory inference algorithms. 

I would say the current most reliable way to benchmarking the trajectory inference tools is to evaluate if the inferred "pseudo-time" correlates with the ground truth trajectory in the simulation.

**Comment by PeterZZQ** [comment]
Thanks! Can users obtain the "more fine-grained" time that you mentioned? I haven't found any output that may correspond to this information.
