### ISSUE TITLE
Where to get my own GRN as input?

### ISSUE THREAD

**Issue by qianxu05172019** [PayamDiba/SERGIO#5]
Hi,

I am wondering where I can download or generate the GRN file for a specific cell type as the input file for SERGIO?

**Comment by PayamDiba** [comment]
If you do not have a particular GRN, you can always use the sample GRNs that we provided in "data_sets" folder.

But, if you have a particular GRN structure that want to simulate you can easily convert it to input files suitable for SERGIO. All you need to do is to convert it into a proper format that SERGIO expects for "input_file_taregts" (please see README to find this file format). You also need to find the master regulators (MR) in your GRN and prepare a "input_file_regs" file that has one row for each MR and columns showing production rates in different cell-types (please see README).

We understand that users might like to use their own GRN structure and hypothetical cell-types compositions and it requires a converter that automatically prepares SERGIO's input file from user files. We apologize for not having such a functionality at the moment but we will work on this in the near future.

**Comment by qianxu05172019** [comment]
Got you. thanks for your reply!
